language: cpp

matrix:
  include:
  - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

  - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - libc++-dev
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0 && CXX_FLAGS=-stdlib=libc++"

  - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"
  
  - os: osx
      osx_image: xcode10.1
    
  - os: osx
      osx_image: xcode9.4

before_install:
  - eval "${MATRIX_EVAL}"

dist: trusty
sudo: false

script:
  - cd tests
  - cmake ./
  - cmake --build . -- VERBOSE=1
  - ./ftl_tests

