language: cpp

matrix:
  include:
  - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cd tests
  - cmake ./
  - cmake --build . -- VERBOSE=1
  - ./ftl_tests

