language: cpp
matrix:
  include:
  - os: linux
    compiler: g++-7
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - LINKER_FLAGS=""

  - os: linux
    compiler: g++-8
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - LINKER_FLAGS=""

  - os: linux
    compiler: clang-5
    addons:
      apt:
        sources: 
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-5.0
        packages:
          - clang-5.0
          - libc++-dev 
          - libc++abi-dev
    env: 
      - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

  - os: linux
    compiler: clang-6
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-6.0
        packages:
          - clang-6.0
          - libc++-dev 
          - libc++abi-dev
    env:
      - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

  - os: osx
    osx_image: xcode10.1
    
  - os: osx
    osx_image: xcode9.4

before_install:
- eval "${MATRIX_EVAL}"

dist: trusty
sudo: false

script:
  - cd tests
  - cmake ./
  - cmake --build . -- VERBOSE=1
  - ./ftl_tests

