language: cpp
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
    env:
      - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

  - os: linux
    addons:
      apt:
        sources:
          - llvm-toolchain-trusty-5.0
        packages:
          - clang-5.0
    env:
      - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-6.0
          - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
          key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
        packages:
        - clang-6.0
        - libstdc++-7-dev
    env:
      - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

  - os: osx
    osx_image: xcode8
    env:
      - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cd tests
  - cmake -DCMAKE_EXE_LINKER_FLAGS=${LINKER_FLAGS} ./
  - cmake --build . -- VERBOSE=1
  - ./ftl_tests

