language: cpp
matrix:
  include:
  - os: windows
    env:
      - MSBUILD_PATH="c:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"
      - MSBUILD_PATH2="c:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin"
    script:
      - export PATH=$PATH:$MSBUILD_PATH:$MSBUILD_PATH2
      - cd tests
      - cmake ./
      - msbuild.exe FTL.sln /p:Configuration=Release
      - ./Release/ftl_tests.exe     

  - os: linux
    compiler: g++-5
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
    env:
    - MATRIX_EVAL="CXX=g++-5"
    - LINKER_FLAGS=""

  - os: linux
    compiler: g++-7
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    env:
    - MATRIX_EVAL="CXX=g++-7"
    - LINKER_FLAGS=""

  - os: linux
    compiler: g++-8
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
    env:
    - MATRIX_EVAL="CXX=g++-8"
    - LINKER_FLAGS=""

  - os: linux
    compiler: clang-3.6
    addons:
      apt:
        sources: 
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-3.6
        packages:
          - clang-3.6
          - libstdc++-7-dev
    env: 
      - MATRIX_EVAL="CXX=clang++-3.6"

  - os: linux
    compiler: clang-4
    addons:
      apt:
        sources: 
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-4.0
        packages:
          - clang-4.0
          - libstdc++-7-dev
    env: 
      - MATRIX_EVAL="CXX=clang++-4.0"

  - os: linux
    compiler: clang-5
    addons:
      apt:
        sources: 
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-5.0
        packages:
          - clang-5.0
          - libstdc++-7-dev
    env: 
      - MATRIX_EVAL="CXX=clang++-5.0"

  - os: linux
    compiler: clang-6
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-6.0
        packages:
          - clang-6.0
          - libstdc++-8-dev
    env:
      - MATRIX_EVAL="CXX=clang++-6.0"

  - os: osx
    osx_image: xcode10.1
    
  - os: osx
    osx_image: xcode9.4

before_install:
- eval "${MATRIX_EVAL}"

dist: trusty
sudo: false

script:
  - cd tests
  - cmake ./
  - cmake --build . -- VERBOSE=1
  - ./ftl_tests

